# Generated by Django 5.2.15 on 2026-06-11 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_description', models.TextField(help_text='The original task prompt given to the pipeline.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('MAX_ITER', 'Max Iterations Reached')], db_index=True, default='PENDING', max_length=10)),
                ('iteration_count', models.IntegerField(default=0)),
                ('max_iterations', models.IntegerField(default=7)),
                ('final_output', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pipeline Run',
                'verbose_name_plural': 'Pipeline Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CritiqueSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iteration', models.IntegerField()),
                ('planner_critique', models.TextField(blank=True, default='')),
                ('reasoner_critique', models.TextField(blank=True, default='')),
                ('merged_critique', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critiques', to='orchestration.pipelinerun')),
            ],
            options={
                'verbose_name': 'Critique Snapshot',
                'verbose_name_plural': 'Critique Snapshots',
                'ordering': ['-iteration'],
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(choices=[('ORCHESTRATOR', 'Orchestrator'), ('PLANNER', 'Planner'), ('REASONER', 'Reasoner'), ('REVIEWER', 'Reviewer'), ('WRITER', 'Writer'), ('EDITOR', 'Editor'), ('CRITIQUE', 'Final Critique')], db_index=True, max_length=20)),
                ('iteration', models.IntegerField()),
                ('input_text', models.TextField()),
                ('output_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='SUCCESS', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orchestration.pipelinerun')),
            ],
            options={
                'verbose_name': 'Agent Log',
                'verbose_name_plural': 'Agent Logs',
                'ordering': ['created_at'],
            },
        ),
    ]
